services:
  db-users:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - $DB_USERS_HOST_PORT:5432
    volumes:
      - user_repository:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 10

  user-auth:
    depends_on:
      db-users:
        condition: service_healthy
    image: user-auth-awizacje
    build:
      context: ./
      args:
        USER_SERVICE_PORT: $USER_SERVICE_PORT
    ports:
     - $USER_SERVICE_HOST_PORT:$USER_SERVICE_PORT
    env_file: .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  user_repository:
    name: $USERS_DB_VOLUME_NAME
