services:
  db-users:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - user_repository:/var/lib/postgresql/data

  user-auth:
    image: user-auth-awizacje
    build:
      context: ./
      args:
        USER_SERVICE_PORT: $USER_SERVICE_PORT
    ports:
     - $USER_SERVICE_HOST_PORT:$USER_SERVICE_PORT
    env_file: .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  user_repository:
    name: $USERS_DB_VOLUME_NAME
